export const INCREMENT_EVENT = "INCREMENT_EVENT";
export const DECREMENT_EVENT = "DECREMENT_EVENT";
export const ADDITION_EVENT = "ADDITION_EVENT";
export const SUBTRACTION_EVENT = "SUBTRACTION_EVENT";
export const ADDRESULT_EVENT = "ADDRESULT_EVENT";
export const DELETERESULT_EVENT = "DELETERESULT_EVENT";